index:
    path: /
    controller: App\Controller\HeadlineController::index
search:
    path: /search
    controller: App\Controller\SearchController
category.general:
    path: /general
    controller: App\Controller\CategoryController::getGeneral
category.business:
    path: /business
    controller: App\Controller\CategoryController::getBusiness
category.entertainment:
    path: /entertainment
    controller: App\Controller\CategoryController::getEntertainment
category.health:
    path: /health
    controller: App\Controller\CategoryController::getHealth
category.science:
    path: /science
    controller: App\Controller\CategoryController::getScience
category.sports:
    path: /sports
    controller: App\Controller\CategoryController::getSports
category.tech:
    path: /tech
    controller: App\Controller\CategoryController::getTech